### PR TITLE
Added additional resources

### PR DESCRIPTION
**Pull request by jfarbowitz**

### CODE REVIEW

**Review by retokromer — COMMENTED** [review]
Should this not be inserted in alphabetical order rather than at the end of the sections?

**Review by dericed — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Comment by jfarbowitz** [comment]
Hi @retokromer ! The resources are not in alphabetical order, I decided to approximate chronological order. Hope that's ok.

**Comment by kfrn** [comment]
Hi @jfarbowitz, thanks for these additions! 

Apologies, the order for the Articles is a little unclear - it's chronological, but each entry begins with the author's surname ¯\_(ツ)_/¯

I'm wondering if the Guggenheim Conserving Computer-Based Art Initiative link more belongs under  **Institutions/Organizations**? There's already an entry for the Guggenheim there, but only to their TBMA Initiative, not CCBA.

**Comment by jfarbowitz** [comment]
Hi @kfrn. Thanks for chiming in. I made the change you suggested with CCBA. Can this be merged?

**Review by retokromer — APPROVED** [review]

**Comment by kfrn** [comment]
Thanks very much, @jfarbowitz!
If you have any more entries in future, please keep them coming :)

**Pull request merged**
