### PR TITLE
Added 3 items

### PR DESCRIPTION
**Pull request by amybbklyn**
Added "Inside Installations" project archive of case studies and guidelines for practice. Added "Collecting and Conserving Performance Art" conference.

### CODE REVIEW

**Comment by kfrn** [comment]
Cool! Just one small correction needed: the links are not formed correctly - I think you have a gap in between the [] and the () in the links.

ii-link

**Comment by retokromer** [comment]
Why has this been closed?

**Comment by amybbklyn** [comment]
Will fix URLs...

**Comment by retokromer** [comment]
Just delete the space between `] (` and it will be perfect!

**Review by retokromer — APPROVED** [review]

**Comment by retokromer** [comment]
Thank you very much, @amybbklyn!

**Comment by amybbklyn** [comment]
Thanks!

**Comment by ablwr** [comment]
WOOOOOOOO thanks!!!

**Comment by kfrn** [comment]
THanks very much @amybbklyn! :tada:

**Pull request merged**
