### PR TITLE
comma

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by retokromer** [comment]
@kfrn In English: is `c.` or `ca.` the canonical abbreviation of `circa`? and is it followed by a space or not?

**Comment by privatezero** [comment]
Just my 2 cents - not sure if it is regional, but I always used `ca.` followed by a space. But also was discouraged from using the abbreviation and always wrote out `circa` in cataloging.

**Comment by retokromer** [comment]
Thank you, ca. followed by a space is usual in the languages I am more familiar in (Italian, German, French)… therefore it’s typographically/aesthetically what my eyes prefer!

**Comment by kfrn** [comment]
I think **c.** is more common where I live, but either works!

**Comment by retokromer** [comment]
Thank you! With or without a following space?

**Comment by kfrn** [comment]
With trailing space, I think! I'm about to add a couple more things, so I'll fix it then :)

**Comment by retokromer** [comment]
OK, thank you, then I’ll not do it.

**Pull request merged**
