### PR TITLE
Symposia: add TechFocus IV (3D-printed art)

### PR DESCRIPTION
**Pull request by kfrn**

### CODE REVIEW

**Comment by retokromer** [comment]
Do we also include future events?

**Comment by kfrn** [comment]
> Do we also include future events?

I think I've added events in advance before. I see no reason not to!

(Also, hi @retokromer! In fact I tried to tag you, but your name didn't come up in the reviewer list. I should have know than you'd see this, though :)

**Comment by retokromer** [comment]
The reason I see in this case is that no resource is freely available yet, if I am not wrong.

(I have been partially blocked two years ago on AMIA Open Source. I guess that’s the reason why you cannot see my name.)

**Comment by kfrn** [comment]
> The reason I see in this case is that no resource is freely available yet, if I am not wrong.

For symposia, I think it's valuable to mark their occurrence, whether there are associated resources or not - it's still a significant occurrence in the TBMA field.

> (I have been partially blocked two years ago on AMIA Open Source. I guess that’s the reason why you cannot see my name.)

I've given you write access to this repo! 👍

**Review by ablwr — APPROVED** [review]

**Review by retokromer — APPROVED** [review]

**Comment by kfrn** [comment]
Thanks @retokromer & @ablwr !

**Comment by privatezero** [comment]
Eeek! Sorry I missed this and am late to the party! I see @retokromer and @ablwr were on point though!

**Comment by kfrn** [comment]
No worries @privatezero !

**Pull request merged**
